# ansible_host: 173.161.34.217 
# ansible_port: 5000 
# ansible_user: ismoil 
# ansible_ssh_pass: Martian123!
# ansible_become_password: Martian123!

ansible_host: 127.0.0.1 
ansible_connection: local
ansible_ssh_pass: Martian123!
ansible_become_password: Martian123!