---
- name:  apply deployment.yaml
  command: kubectl delete -f /home/ismoil/Projects/{{project.deployment_name}}.yaml

- name:  delete deployment.yaml
  command: kubectl apply -f /home/ismoil/Projects/{{project.deployment_name}}.yaml