---
- name:  delete deployment.yaml
  command: kubectl apply -f /home/ismoil/Projects/deployment.yaml

- name:  apply deployment.yaml
  command: kubectl delete -f /home/ismoil/Projects/deployment.yaml