all:
  children:




    kube_node:
      hosts:
        0.0.0.0:
          ansible_user: ubuntu8
          ansible_ssh_pass: password
          ansible_ssh_port: 22 
          hostname: 




    zabbix_server:
      hosts:
        0.0.0.0:
          ansible_user: root
          ansible_ssh_pass: password
          ansible_ssh_port: 22
          hostname:
        
    zabbix_agents:
      hosts:
        0.0.0.0:
          ansible_user: ubuntu8
          ansible_ssh_pass: password
          ansible_ssh_port: 22 
          hostname: 





    kafka_servers:
      hosts:
        0.0.0.0:
          ansible_user: ubuntu8
          ansible_ssh_pass: password
          ansible_ssh_port: 22 
          hostname: 
    rabbitmq_servers:
      hosts:
        0.0.0.0:
          ansible_user: ubuntu8
          ansible_ssh_pass: password
          ansible_ssh_port: 22 
          hostname:

