- name: Install Java (required for Kafka)
  apt:
    name: openjdk-17-jdk
    state: present

- name: Download Kafka tarball
  get_url:
    url: https://downloads.apache.org/kafka/3.5.1/kafka_2.13-3.5.1.tgz
    dest: /tmp/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: /opt
    remote_src: yes

- name: Create symbolic link for Kafka
  file:
    src: /opt/kafka_2.13-3.5.1
    dest: /opt/kafka
    state: link
