- name: Add RabbitMQ repository
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian buster main"
    state: present

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
    state: present

- name: Ensure RabbitMQ is running
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
