---
- name: Install Zabbix Agent dependencies
  apt:
    name:
      - wget
      - lsb-release
    state: present

- name: Download Zabbix release .deb package
  ansible.builtin.get_url:
    url: "https://repo.zabbix.com/zabbix/6.3/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.3-3%2Bubuntu22.04_all.deb"
    dest: "/tmp/zabbix-release.deb"

- name: Install the Zabbix release .deb package
  ansible.builtin.apt:
    deb: "/tmp/zabbix-release.deb"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Zabbix Agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: Configure Zabbix Agent configuration file
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify:
    - Restart Zabbix Agent

- name: Start and enable Zabbix Agent service
  service:
    name: zabbix-agent
    state: started
    enabled: yes

