---
- name: Install Zabbix Server dependencies
  apt:
    name:
      - wget
      - lsb-release
    state: present

- name: Add Zabbix repository
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu $(lsb_release -c | awk '{print $2}') main"
    state: present

- name: Install Zabbix Server and Frontend
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - mysql-server
    state: present
    update_cache: yes

- name: Configure Zabbix Server DB
  mysql_db:
    name: zabbix
    state: present
    collation: utf8_bin
    encoding: utf8

- name: Import Zabbix database schema
  command: "zcat /usr/share/doc/zabbix-sql-scripts/mysql/create.sql.gz | mysql -uzabbix -p{{ zabbix_db_password }} zabbix"
  args:
    creates: /var/lib/mysql/zabbix

- name: Configure Zabbix Server configuration file
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify:
    - Restart Zabbix Server

- name: Start and enable Zabbix Server service
  service:
    name: zabbix-server
    state: started
    enabled: yes
