- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Cache validity period in seconds

- name: Install required dependencies
  apt:
    name:
      - wget
      - ca-certificates
      - curl
    state: present

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main"
    state: present
    filename: "pgdg"

- name: Add PostgreSQL repository key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present

- name: Ensure PostgreSQL is started and enabled on boot
  service:
    name: postgresql
    state: started
    enabled: yes
